packages/event-listener/src/index.ts

Changed createEventListener types a bit: now when creating an event listener, the handler's event prop will have a correct type.
Before:
Now:
Also added `options` property to createEventListener function, for passing options to addEventListener, like `{passive: false}`.

event-listener options & better handler event type

---

packages/intersection-observer/src/index.ts

some changes to the intersection-observer module to improve usability:
Non-breaking changes: 
- the `elements` argument now also accepts function.
This is so that createIntersectionObserver could be called without wrapping it with onMount when we want to pass in a ref, since onMount is used internally anyway.
- improved onChange callback type
- added a new helper function — createVisibilityObserver — to reduce the amount of code that has to be written just to observe if a single element is on a screen.
Breaking changes:
- combined root, rootMargin & threshold arguments into single `options` object. so that it matches the native IntersectionObserver api.
- changed the return values from being a 4-5 item tuple into an object. I think it's just easier to destructure and use it like that.

Intersection observer improvements

---

packages/intersection-observer/README.md
packages/intersection-observer/src/index.ts
packages/intersection-observer/test/index.test.ts

I realized that the `start` function from createViewportObserver wasn't actually doing anything, since the initial array of elements passed to the createIntersectionObserver is empty. So now "restarting" should work similarly to createIntersectionObserver.
Also fixed some issues in the usage section in the readme.

fix readme & createViewportObserver start

---

package.json
packages/event-listener/src/index.ts
packages/event-listener/test/index.test.ts

This
- adds a script to run all tests in all packages from the root of the repo.
- fixes several type errors.
Tests are not yet passing, there is a runtime error.
To try it, run the following at the root of the repo:
```sh
npm install
npm test
```
You will see tests exit with a runtime error inside the `event-listener` tests.

add test script to run all tests

---

packages/resize-observer/src/index.ts

Noticed the untyped callback when using this primitive.

Add missing type to ResizeObserver

---

packages/map/LICENSE
packages/map/README.md
packages/map/dev/index.html
packages/map/dev/index.tsx
packages/map/dev/tsconfig.json
packages/map/dev/vite.config.ts
packages/map/package.json
packages/map/src/index.ts
packages/map/test/index.test.ts
packages/map/tsconfig.json
packages/map/tsup.config.ts

If there is a [Set](#65) there has to be a Map. The same concepts, the same architecture.
Here is a snippet:
```ts
const userPoints = new ReactiveMap<User, number>();
// reads can be listened to reactively
createEffect(() => {
userPoints.get(user1); // => T: number | undefined (reactive)
userPoints.has(user1); // => T: boolean (reactive)
// ReactiveWeakMap won't have .size or any methods that loop over the values
userPoints.size; // => T: number (reactive)
});
// apply changes
userPoints.set(user1, 100);
userPoints.delete(user2);
// setter works similarly as signal's
userPoints.set(user1, n => n * 10);
// mutations are NOT tracked:
map.get("John").age = 35;
```
[The readme](https://github.com/davedbase/solid-primitives/tree/map/packages/map#solid-primitivesmap)

New package: Map

---

packages/raf/src/index.ts

It's running the loops twice when calling manually to `start()` without setting runImmediately to `false`
runImmediately is to true by default. This means that the loop would be running. If you then call `start()` like in the example provided
```js
const [running, start, stop] = createRAF(() => console.log('hi')));
start();
```
Then you will have two loops running, as `start()` doesn't check if the RAF is currently running. The animation will run twice as fast.
disclaimer: I only tested this on the playground provided by manually calling `start()` right after createRAF

[RAF] fix: it's running the loops twice 

---

packages/input-mask/dev/index.html
packages/input-mask/dev/index.tsx
packages/input-mask/src/index.ts

Small fix (for "a" in string masks not to match numbers) and improvements for the demo page when running `yarn dev`.

improve input mask

---

packages/event-listener/README.md

I had to read the code to check whether this was the case: `createEventListener` can take standard `let` refs. The current examples use `document.getElementById` and signal refs, but not normal refs.

Document event-listener w.r.t. refs

---

packages/fetch/README.md
packages/fetch/package.json
packages/fetch/src/server.ts
packages/fetch/tsconfig.json

To handle issue#88, I changed the server entry so that node-fetch was only required once fetch was called for the first time, with a soft failure function emitting just a nice console message and rejecting every request.
I've used the same pattern in solid-register for optional dependencies and found it very effective.

make node-fetch optional

---

packages/rootless/README.md
packages/rootless/package.json
packages/rootless/src/index.ts
packages/rootless/test/index.test.ts
packages/rootless/tsconfig.json

This PR brings the refactor brought up in #102.
This will allow us to push more the pattern of using `createDisposable` or `createBranch` for disposing computations early, and proceed with clean() function refactor mentioned here: #103 
As this is a breaking change I've bumped the version to `1.0.0`, and the package stage to 2.

rootless: refactor `runWith___` functions (closes #102)

---

packages/rootless/README.md
packages/rootless/package.json
packages/rootless/src/index.ts
packages/rootless/test/index.test.ts
packages/rootless/tsconfig.json

This brings a new primitive to the `rootless` package.
A shared root allows for reusing the computations/signals/event-listeners across primitive dependents. Useful for "global primitives" like `createDevices`, `createMouse`, `createLocationState` – all instances would produce the same state.
Example usage with `createDevices`
```ts
const useDevices = createSharedRoot(() => createDevices())
// in first dependency – primitive is first executed:
const devices = useDevices()
// in every other dependency – primitive is being reused:
const devices = useDevices()
// once every dependency get's disposed – the primitive will be also disposed
// and recreated when a new dependency uses it
```
[the readme](https://github.com/solidjs-community/solid-primitives/tree/feature/rootless-shared-root/packag …

Rootless: new `createSharedRoot` primitive

---

packages/input-mask/README.md
packages/input-mask/package.json
packages/input-mask/src/index.ts

A few minor improvments for input-mask, documented in the README.

input-mask: exposed string regexps and generics

---

packages/input-mask/README.md
packages/input-mask/dev/index.tsx
packages/input-mask/src/index.ts
packages/input-mask/test/index.test.tsx

I found an even more more elegant solutions to masks that replace parts using string.replace(regex, fn). Also, I implemented a few byte-saving techniques to further reduce the bundle size so that we still remain close to 0.5kb even with the added functionality.

input-mask: support regex-replace masks

---

.github/workflows/tests.yml
.github/workflows/update-readme.yml
README.md
lerna.json
package.json
packages/active-element/package.json
packages/connectivity/package.json
packages/context/package.json
packages/event-listener/package.json
packages/gestures/package.json
packages/immutable/package.json
packages/immutable/test/index.test.ts
packages/input-mask/package.json
packages/intersection-observer/package.json
packages/map/package.json
packages/media/package.json
packages/memo/package.json
packages/mouse/package.json
packages/pointer/package.json
packages/raf/package.json
packages/range/package.json
packages/reducer/package.json
packages/selection/package.json
packages/set/package.json
packages/timer/package.json
pnpm-workspace.yaml
template/package.json

pnpm workspaces for installation, instead of lerna bootstrap
gh actions will use pnpm as well
mac-os and windows were removed from the testing gh action – running the scripts was taking infinite amount of time there for some reason
this also makes the testing gh action work (on the main branch the tests were always failing for no reason)

yarn -> pnpm

---

packages/upload/src/index.ts

I made the `index.ts` export all the types of `@solid-primitives/upload` from `types.ts`.
I don't know whether all the types should be exported, or some should be left accessible only inside the package, so maybe some changes should be made

Upload: export types

---

packages/visibility-observer/README.md
packages/visibility-observer/package.json
packages/visibility-observer/src/index.ts
packages/visibility-observer/src/server.ts
packages/visibility-observer/test/index.test.ts
packages/visibility-observer/tsconfig.json

- Rename `createPageVisibilityObserver` to `createPageVisibility` _(no longer exported as default)_
- Add `usePageVisibility`
- Add tests
[README](https://github.com/solidjs-community/solid-primitives/tree/visibility-observer-refactor/packages/visibility-observer#readme)

Refactor visibility-observer

---

packages/storage/src/storage.ts
packages/storage/test/storage.test.ts

Before you had to do:
```ts
const [getValue] = createStorageSignal<string, {}>("value");
```
Now you can do:
```ts
const [getValue] = createStorageSignal<string>("value");
```

storage: Set options default type to {}

---

packages/event-listener/README.md
packages/event-listener/src/callbackWrappers.ts
packages/event-listener/src/index.ts

Three very small helpers, but I like to use them personally. Maybe because I had `@click.prevent="callback"` in vue.
[README](https://github.com/solidjs-community/solid-primitives/tree/cb-wrappers/packages/event-listener#callback-wrappers-1)

Add callback wrappers to event-listener

---

packages/keyboard/LICENSE
packages/keyboard/README.md
packages/keyboard/dev/index.html
packages/keyboard/dev/index.tsx
packages/keyboard/dev/vite.config.ts
packages/keyboard/package.json
packages/keyboard/src/env.d.ts
packages/keyboard/src/holdKeyListener.ts
packages/keyboard/src/index.ts
packages/keyboard/src/server.ts
packages/keyboard/test/index.test.ts
packages/keyboard/tsconfig.json
packages/keyboard/tsup.config.ts

This adds a new package: **keyboard**
There is much more that can be added here, but for now, I'm just adding what I need.
And what I need is: `makeHoldKeyListener`
```tsx
const [pressing, setPressing] = createSignal(false);
makeKeyHoldListener("altKey", setPressing, {
preventDefault: true
});
<p>Is pressing <kbd>Alt/Option</kdb>? {pressing() ? "YES" : "NO"}</p>;
```
[README](https://github.com/solidjs-community/solid-primitives/tree/keyboard/packages/keyboard#readme)

add `keyboard` package with `makeKeyHoldListener`

---

packages/props/README.md
packages/props/package.json
packages/props/src/filterProps.ts
packages/props/src/index.tsx
packages/props/src/propTraps.ts
packages/props/test/filterProps.test.ts

Adds `filterProps` and `createPropsPredicate` primitives to the props package.
The idea of `filterProps` comes from the [`filterDOMProps`](https://github.com/solidjs-community/solid-aria/blob/main/packages/utils/src/filterDOMProps.ts#L58) helper in solid-aria, and will be used to update it.
[README](https://github.com/solidjs-community/solid-primitives/tree/filter-props/packages/props#filterprops)

Props: add `filterProps` primitive

---

packages/fetch/src/index.ts

Since v1.4.0 you can use deferStream so Solid waits for resource before flushing to stream, however this package doesn't support this with its types.

chore(fetch): add defer stream to FetchOptions

---

.changeset/large-spoons-heal.md
packages/fetch/package.json
packages/fetch/src/server.ts

The side effect was impacting tree shaking. Thanks to the composable update, we can now easily remove the global polyfill.

fetch: remove side-effects

---

.changeset/twelve-cobras-rhyme.md
packages/stream/src/index.ts

Moved amplitude logic from `createAmplitudeStream` to `createAmplitudeFromStream` So it can be used with third party MediaStream. Also removed audio sample rate so it will defaults to device's preferred sample rate.

Created `createAmplitudeFromStream`

---

packages/cursor/LICENSE
packages/cursor/README.md
packages/cursor/dev/App.tsx
packages/cursor/dev/index.html
packages/cursor/dev/index.tsx
packages/cursor/dev/vite.config.ts
packages/cursor/package.json
packages/cursor/src/index.ts
packages/cursor/src/server.ts
packages/cursor/test/exports.test.ts
packages/cursor/test/index.test.ts
packages/cursor/tsconfig.json
packages/cursor/tsup.config.ts
packages/cursor/vite.config.ts
vite.config.ts

Adds two simple primitives for setting the cursor CSS property reactively to document body, or selected HTML Element.
```ts
import { createElementCursor } from "@solid-primitives/cursor";
const target = document.querySelector("#element");
const [cursor, setCursor] = createSignal("pointer");
const [enabled, setEnabled] = createSignal(true);
createElementCursor(() => enabled() && target, cursor);
setCursor("help");
```
[README](https://github.com/solidjs-community/solid-primitives/tree/cursor/packages/cursor#readme)
TODO:

New package: Cursor

---

.changeset/dull-baboons-kick.md
packages/idle/src/createIdleTimer.ts

Configuration argument is supposed to be optional, however calling `createIdleTimer()` without any argument would result in error. This shall fix it.

quickfix: config object is supposed to be optional

---

.changeset/chatty-cycles-rush.md
packages/websocket/src/index.ts

packages/websocket/src/index: Updated the reconnectLimit  to NEGATIVE_INFINITY to avoid reconnection on calling disconnect function

Updated the reconnectLimit to avoid reconnection on calling disconnect function

---

template/dev/vite.config.ts

Fix vite config path on new-package script. The current path is incorrect and causes dev script on created package to fail.

Fix vite config path on new-package script

---

packages/input-mask/README.md

They changed the header in the article, so the hash part wasn't correct anymore. Although I just noticed that if you open the link, it doesn't scroll to the header anyway, so maybe this change is useless.

Updated the link to mozilla.org

---

.changeset/selfish-cycles-serve.md
packages/audio/src/index.ts

This can happen when trying to play audio prior to the user interacting with the page.
Should we be treating this the same as we do any other error or does it warrant a special case which will allow library users to, e.g., show a popup which when dismissed will retry playback?
I've also made this only happen if the exception thrown is named `NotAllowedError`, which is the name of the error thrown when the user agent blocks playback (e.g. because the user didn't interact with the page).
Should this just be a catch-all `catch`?
(Also the current implementation might need to rethrow errors that aren't named `NotAllowedError` but it's a trivial change to make)

Handle exceptions thrown during audio playback

---

.changeset/witty-buses-hug.md
packages/tween/src/index.ts

Type declaration file in build had incorrect type:
@solid-primitives/tween/dist/index.d.ts
```
declare function createTween<T extends number>(target: () => T, { ease, duration }: {
ease?: ((t: T) => T) | undefined;
duration?: number | undefined;
}): () => void;
```

fix: specify createTween return type

---

.changeset/many-buckets-grin.md
packages/jsx-parser/src/index.ts

[as discussed here](https://github.com/solidjs-community/solid-primitives/pull/276#issuecomment-1407043412)

jsx-parser: set returnType createToken from JSX.Element to TokenComponent<Token>

---

scripts/update-readme.ts

The links on the stage shields are broken. They are pointing to a chapter **contribution process** which does not exist on the main `README.md` file.
However this chapter exists in the `CONTRIBUTING.md` file.

docs(readme): update the link on the stage shields

---

.changeset/nasty-camels-roll.md
packages/script-loader/CHANGELOG.md
packages/script-loader/README.md
packages/script-loader/package.json
packages/script-loader/src/index.ts
packages/script-loader/test/index.test.ts
packages/script-loader/test/server.test.ts

Add `onBeforeAppend` callback option. Rename onload and onerror to onLoad and onError. Do not return the remove script function - should be done with disposing the owner. React to src changes with createRenderEffect.

script-loader: Improve API, spread any props on to the script

---

.changeset/great-moons-explain.md
.changeset/light-wolves-remember.md
packages/jsx-parser/README.md
packages/jsx-parser/dev/index.tsx
packages/jsx-parser/package.json
packages/jsx-parser/src/index.ts
packages/jsx-parser/test/index.test.tsx
packages/jsx-parser/test/server.test.tsx
packages/utils/src/types.ts
pnpm-lock.yaml

@bigmistqke I think that the parser needs to be updated.
Haven't realized this previously but currently, the token data is being restructured and spread on the token with `Object.assign`. This is needlessly more expensive and prevents adding getters to the top-level object. Not only does getter, it just breaks the reference of the passed object.
First, this would be a weird issue to walk into if you have no idea how things get applied, and second, it isn't consistent with other solid APIs (context, props) where adding getters to passed object is common practice.
Also made it so that if you don't pass the function for creating the data object, the component props will be used as the object. Which is great if you only need one token in your api.

jsx-parser: Add the data to the `data` property

---

.changeset/forty-pigs-lick.md
packages/clipboard/README.md
packages/clipboard/dev/index.tsx
packages/clipboard/dev/vite.config.ts
packages/clipboard/package.json
packages/clipboard/src/index.ts
packages/clipboard/src/types.d.ts
packages/clipboard/test/index.test.ts
packages/clipboard/test/setup.ts

- Stop reading from the clipboard initially. (Fixes #256)
- Simplify item value returned by createClipboard.
- Add `writeClipboard` and `readClipboard` as standalone functions. (deprecate `makeClipboard` - it's useless as read and write can be exported on their own)
the docs still need to be updated I guess
I hope this doesn't mess with the createClipboard API too much...

clipboard: Minor improvements, fix #256

---

.changeset/rare-tables-whisper.md
package.json
packages/rootless/package.json
packages/rootless/src/index.ts
pnpm-lock.yaml

From version Solid v1.6.11 createRoot now correctly handles `null` values as detachedOwner in createRoot. It should be allowed to createSubRoots with `null` owner in order to not inherit the context.

Allow for passing `null` to `createRoot` in `createSubRoot`.

---

packages/autofocus/LICENSE
packages/autofocus/README.md
packages/autofocus/dev/index.html
packages/autofocus/dev/index.tsx
packages/autofocus/dev/vite.config.ts
packages/autofocus/package.json
packages/autofocus/src/index.ts
packages/autofocus/test/index.test.tsx

Solid does not natively support the `autofocus` attribute. This PR adds a new package with 2 new primitives to support it.
`@solid-primitives/autofocus`:
- `use:autofocus` a directive to use on HTML components.
- `createAutofocus` a ref based autofocus for custom components.
See [autofocus/README](https://github.com/jer3m01/solid-primitives/blob/feat/autofocus/packages/autofocus/README.md) for more details and examples.
The `use:autofocus` directive uses the native `autofocus` attribute to decide on focusing. This provides a seamless integration with existing code<sup>1</sup>, but might come as repetitive/confusing (`use:autofocus autofocus`). Let me know what you think! 
1: Add `use:autofocus` and, provided the intrinsic props are passed down, no extra logic is required.

feat: new autofocus primitive

---

.changeset/bright-timers-trade.md
package.json
packages/scheduled/README.md
packages/scheduled/dev/index.tsx
packages/scheduled/dev/reactive.tsx
packages/scheduled/dev/timeline.tsx
packages/scheduled/package.json
packages/scheduled/src/index.ts
packages/scheduled/test/create-scheduled.test.ts
packages/scheduled/test/debounce.test.ts
packages/scheduled/test/sleep.ts
packages/scheduled/test/throttle.test.ts
pnpm-lock.yaml

Adds new `createScheduled` primitive to the `scheduled` package based on @fabiospampinato's idea.
It provides a nice API for composing scheduling with any scheduling primitive (`debounce`, `throttle`, `scheduleIdle`, etc.) and any solid computation primitive.
```ts
import { createScheduled, debounce } from "@solid-primitives/scheduled";
const scheduled = createScheduled(fn => debounce(fn, 1000));
const [count, setCount] = createSignal(0);
createEffect(() => {
// track source signal
const value = count();
// track the debounced signal and check if it's dirty
if (scheduled()) {
console.log("count", value);
}
});
// or with createMemo
const debouncedCount = createMemo((p: number = 0) => {
// track source signal
const value = count();
// track the debounced signal and check if it's dirty …
```

scheduled: Add `createScheduled` primitive

---

.changeset/twenty-glasses-act.md
packages/active-element/package.json
packages/active-element/src/index.ts
packages/connectivity/package.json
packages/connectivity/src/index.ts
packages/media/package.json
packages/media/src/index.ts
packages/page-visibility/package.json
packages/page-visibility/src/index.ts
packages/share/package.json
packages/share/src/web-share.ts
packages/styles/package.json
packages/styles/src/index.ts
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/test/index.test.ts
packages/utils/test/server.test.ts
pnpm-lock.yaml

Following https://github.com/solidjs-community/solid-primitives/issues/310
New `createHydrateSignal` with test on `utils:package`
Fixes hydration issue and improve shared root usage on : 
- `createMediaQuery` & `usePrefersDark`
- `createActiveElement` & `createFocusSignal`
- `createConnectivitySignal` & `useConnectivitySignal`
- `createPageVisibility` & `usePageVisibility`
- `createRemSize` & `useRemSize`
Fixes SSR function return order on `createWebShare`
Thank you @thetarnav for helping on my first contribution, I've tried my best.

utils: new createHydrateSignal - fix:hydration issues

---

.changeset/tame-lions-yell.md
packages/memo/src/index.ts
packages/memo/test/writable.test.ts

Remove `.v` property access on setter return. Also add a test to ensure value returned from setter is the value passed in.

fix createWritableMemo setter return

---

.changeset/twenty-parrots-battle.md
packages/filesystem/src/adapter-mocks.ts
packages/filesystem/src/adapter-node.ts
packages/filesystem/src/adapter-tauri.ts
packages/filesystem/src/adapter-vfs.ts
packages/filesystem/src/adapter-web.ts
packages/filesystem/src/reactive.ts
packages/filesystem/src/types.ts
packages/filesystem/test/index.test.ts
packages/filesystem/test/server.test.ts
packages/filesystem/test/tauri-mock.ts

As previously announced, I wanted to improve the fail case; instead of returning a defunct file system adapter, returning null enables the user to detect if they need another case; this also allows to ||-chain file system adapters.

filesystem: improve fail case

---

site/src/components/Primitives/VersionBadge.tsx
site/src/routes/index.tsx

This PR fixes the issue #393 regarding initial load times & unneccesary fetch requests on the client,
Changes:
1. i've changed the VersionBadge component to accept a `version` prop, which we can use instead of calling `createPackageVersion` which introduced the request flood.
2. i've changed the `route.tsx` (homepage) to pass the `pkg.version` as a prop to `VersionBadge`, which is already available without extra requests.
i'm not used to the codebase so feel free to suggest changes.

site: Performance optimization, fix #393

---

.changeset/quick-plums-punch.md
packages/mutation-observer/src/index.ts
packages/mutation-observer/test/index.test.ts
packages/mutation-observer/test/setup.ts

Since this is a one-line change, I wasn't bothered to post a issue for it.
> **MutationObserver: takeRecords() method**
> The [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) method takeRecords() returns a list of all matching DOM changes that have been detected but not yet processed by the observer's callback function, leaving the mutation queue empty.
> -- <https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/takeRecords>
Therefore `takeRecords()` returns an empty array when there're no pending notifications, canceling the `disconnect()`call.

Fix MutationObserver doesn't disconnect when there're no pending notifications

---

site/src/components/Primitives/InfoBar.tsx
site/src/components/Primitives/VersionBadge.tsx
site/src/routes/package/[name]/(package).tsx

This PR fixes a related issue to #393,
but for the `<VersionBadgePill>` component,
as it also can recieve its `version` resource from the package route,

site: Removes unneccessary fetch from (package).tsx, related #393

---

.changeset/witty-seahorses-boil.md
packages/filesystem/README.md
packages/filesystem/package.json
packages/filesystem/src/adapter-tauri.ts
packages/filesystem/src/tools.ts
packages/filesystem/test/index.test.ts

Filesystems are much more useful if you can connect them. So, in order to do exactly that, I have created a small (421bytes minzipped) rsync utility for the package that allows copying stuff recursively from one file system (or file system adapter) to another.
I also fixed an import for the tauri file system adapter, bringing down its size from 1.43kb to a mere 283bytes minzipped.

filesystem: rsync utility

---

.changeset/kind-maps-notice.md
packages/i18n/README.md
packages/i18n/src/i18n.ts
packages/i18n/src/index.ts

Add `useScopedI18n`, so that we can:
```ts
const dict = {
en: { 
login: {
username: 'User name',
password: 'Password',
login: 'Login'
},
fr: {
...
}
}
}
export const LoginView () => {
const [t] = useScopedI18n('login');
return <>
<div>{t('username')}<input /></div>
<div>{t('password')}<input /></div>
<button>{t('login') }</button>
</>
}
```

i18n: Add useScopedI18n(scope: string)

---

.changeset/brown-needles-enjoy.md
packages/memo/README.md
packages/memo/package.json
packages/memo/src/index.ts
packages/memo/test/latest.test.ts

This adds a missing brother to `createLatest` which had a flaw that from multiple sources updated during a `batch` only the last one would get returned. `createLatestMany` returns an array with all the values updated in the last tick, which is useful if we don't have to ignore any update.
This also deprecates the existing scheduled memos as they can be replaced with a way more composable `createSchedule`

Add `createLatestMany`, deprecate scheduled memos

---

.changeset/warm-bottles-pump.md
packages/i18n/src/i18n.ts
packages/i18n/src/index.ts
packages/i18n/src/types.ts

Add typings for `useI18n`, so that we can:

i18n: Add typings for `useI18n`

---

.changeset/sixty-dryers-float.md
packages/graphql/src/index.ts

The current code passes `initialValue` unconditionally to the `createResource()` function, forcing an initial value even if the corresponding argument is undefined. This is bad because the sequence of states the resource goes through is:
* refreshing
* ready
while with an undefined `initialValue` the sequence is expected to be:
* pending
* ready
This patch fixes this problem and restores the correct resource states by passing a third argument to `createResource()` only when `initialState !== undefined`.

graphql: fix resource states

---

.changeset/bright-cherries-destroy.md
packages/graphql/README.md
packages/graphql/dev/index.tsx
packages/graphql/package.json
packages/graphql/src/index.ts
pnpm-lock.yaml

**Breaking:** The query primitive now accepts a `ResourceOptions` object, instead of just `initialValue`.
Changes to `url` or `options` will invalidate the resource now. Fixes #328
@fogzot

grapgql: resource options and reactive `url`, `options`

---

.changeset/short-pugs-kneel.md
packages/input-mask/README.md
packages/input-mask/dev/index.tsx
packages/input-mask/package.json
packages/input-mask/src/index.ts
packages/input-mask/test/index.test.tsx
pnpm-lock.yaml

Fabio requested the feature to be able to display a pattern mask while editing. Here it is.

input-mask: new pattern display primitive

---

packages/jsx-tokenizer/README.md

fixed link to jsx-tokenizer example (was `https://primitives.solidjs.community/playground/` before)

fix link to jsx-tokenizer example

---

.changeset/giant-steaks-double.md
configs/vitest.config.ts
packages/storage/README.md
packages/storage/dev/index.tsx
packages/storage/package.json
packages/storage/src/cookies.ts
packages/storage/src/index.ts
packages/storage/src/persisted.ts
packages/storage/src/storage.ts
packages/storage/src/types.ts
packages/storage/test/persisted.test.ts
packages/storage/test/tools.test.ts
pnpm-lock.yaml

The storage package was needlessly complex, large and led to frequent misunderstandings from developers who expected it to work like a store. I have learned from my mistakes and deprecated the old APIs with the exception of the cookieStorage. I also added a new smaller `makePersisted(signalOrStore)` primitive that should fulfil the general requirements and improved the cookieStorage.

Storage rewrite

---

packages/state-machine/LICENSE
packages/state-machine/README.md
packages/state-machine/dev/index.tsx
packages/state-machine/package.json
packages/state-machine/src/index.ts
packages/state-machine/test/index.test.ts
packages/state-machine/test/server.test.ts
packages/state-machine/tsconfig.json
pnpm-lock.yaml

A primitive for creating a reactive state machine. For expressing possible states and transitions, and bounding reactive computations to the lifecycle of those states.
This takes a bit different and more minimalistic approach to state machines. Maybe you cannot even call it a state machine. But I think it fits well the already very declarative capabilities of solid's reactivity, and utilizes the lifecycle of computations to scope state relevant logic.
I've been using this pattern when defining app logic that could be described using exclusive states, and relying on solid's reactivity one could very easily achieve that. But the biggest issue were types, defining unions of possible states can be very annoying, and usually will be done inconsistently because of that.
This primitive mainly …

State machine

---

.changeset/warm-ties-cover.md
packages/transition-group/src/index.ts
packages/transition-group/test/switch-transition.test.ts

Correct order of callbacks in parallel switch transition.

transition-group: Correct order of callbacks

---

packages/start/README.md

Added an Examples section to the `README.md` file that includes code snippets from `root.tsx`, `root.css` and `Counter.css`.

Update `start` README with Examples Section for `createUserTheme`

---

.changeset/angry-planes-shout.md
.changeset/fresh-panthers-nail.md
packages/map/src/index.ts
packages/map/test/index.test.ts
packages/set/src/index.ts
packages/set/test/index.test.ts

- `.forEach()` wasn't tracking changes to values, only keys
- `.keys()`, `.entries()` and `.values()` was tracking any changes to keys, even if the key was not seen
Also some were iterating the map twice
- Same for `ReactiveSet`

Fix ReactiveMap iterators tracking

---

.changeset/eleven-roses-smash.md
packages/resize-observer/README.md
packages/resize-observer/dev/index.tsx
packages/resize-observer/src/index.ts

resize-observer: Use `getBoundingClientRect` instead of `contentRect` to get element size on resize in `createElementSize`
Fixes #469

resize-observer: Use `getBoundingClientRect` instead of `contentRect`

---

packages/range/README.md

Docs: fix typo

---

.changeset/little-mails-obey.md
packages/memo/src/index.ts
packages/memo/test/latest.test.ts

Correct `createLatest` and `createLatestMany` triggering on `equals: false` sources

Correct createLatest triggering on equals: false

---

packages/storage/README.md
packages/storage/src/cookies.ts
packages/storage/src/persisted.ts
packages/storage/src/types.ts

Before there were issues when just setting a cookie using storage api on server and you set a custom setCookie it fails when it tries to raise an Event on server, because the URL api is only available on the client.
Additionally i have added full support for the "Set-Cookie" header so that when the server sets a cookie this automatically gets passed to the client. This only works if a PageEvent is returned by getRequest, because i obviously have to access the responseHeaders. I tried to make everything as backwards compatible as possible.
There is one thing to think about in the future, cookies are not only identified by their key, but by the combination of key, path and domain. The code currently and before assumed that key is the only primary identifier.
Now the StorageOptions should be …

Add full ssr cookie support to storage package

---

.changeset/eighty-sheep-travel.md
packages/websocket/src/index.ts

Unfortunately, I forgot to set up the heartbeat after the reconnect. By moving this setup into the open event, it will be repeated for a reconnected web socket connection. This resolves [issue#528](https://github.com/solidjs-community/solid-primitives/issues/528).

websocket: fix heartbeat reconnect

---

.changeset/twenty-bikes-cheer.md
packages/idle/README.md
packages/idle/dev/index.tsx
packages/idle/src/createIdleTimer.ts
packages/idle/src/types.ts
packages/idle/test/index.test.ts

This pull request addresses the issue [#503](https://github.com/solidjs-community/solid-primitives/issues/503).
Currently, the `createIdleTimer` primitive does not provide a way to manually trigger the idle state. This pull request adds a new method called `triggerIdle` to the IdleTimer instance returned this primitive. The `triggerIdle` function sets the `isIdle` state to true, triggers the `onIdle` callback bypassing the prompt phase, and attaches listeners to the specified events that will call the `onActive` function if triggered. 
JSDoc and type definition were improved for better understanding and clarity.
cc. @itamarsch

Add triggerIdle function to manually trigger idle state - Fixes #503

---

.changeset/olive-planets-watch.md
packages/script-loader/src/index.ts
packages/script-loader/test/index.test.ts

A user on discord found the issue that attributes (e.g. data attributes) are not set when using createScriptLoader in hydration. This fixes the behavior.

script-loader: support attributes in hydration

---

.changeset/curly-beds-explode.md
packages/jsx-tokenizer/src/index.ts
packages/refs/src/index.ts
packages/utils/src/types.ts

This commit removes the ResolvedJSXElement and ResolvedChildren type exports from the types.ts file in the utils package. These types were previously imported from the solid-js library but are no longer needed
because now they are properly exported by solid-js.
This may break existing code, but only the imports and nothing else therefore a simple changelog entry should do the trick.
Please consider merging, because my build fails due to this import, because this import doesn't work always when using `pnpm`

Remove unused type exports in utils

---

.changeset/large-beans-sort.md
packages/pagination/dev/index.tsx
packages/pagination/src/index.ts

Loading in infinite scrolling triggers suspense, thus temporarily blanking the demo page whenever the next part is loaded.

fix suspense in infinite scrolling

---

packages/media/CHANGELOG.md
packages/media/README.md
packages/media/package.json
packages/media/src/index.ts
pnpm-lock.yaml

This patch is designed to support older iOS/MacOS Safari browsers that don't support addEventListener on MediaQuery. Since it only supports addListener, we have to add a fallback. The PR changes two details:
1. Removes the `event-listener` package
2. Adds a `makeListener` function replacing `makeEventListener` that uses `addListener` as a callback
3. Cleans up
This patch has passed tests however I haven't not been able to verify that it is fully functional.

Patch Media: Remove event-listenever package and replaced with local function

---

.changeset/stale-llamas-repair.md
packages/storage/src/tools.ts

The `return` statement was removed by mistake in pull https://github.com/solidjs-community/solid-primitives/pull/606
This caused `makePersisted` to use the default value on the server side.
This PR adds back the implicit `return` statement.

Add back the return statement to withOptions

---

.changeset/beige-suits-add.md
packages/deep/src/track-store.ts
packages/deep/test/track.test.ts

Seems like I made an error when writing a test.
`set("a", "a.a", "a.a.b", "thoughts")`
instead of
`set("a", "a.a", "a", "a.b", "thoughts")`
which caused me to make a flawed implementation to satisfy the test 🫠
seems to be good now

Fix `trackStore` tracking multiple same-object references. (Fixes #582)

---

.changeset/dry-tips-kneel.md
packages/raf/README.md
packages/raf/package.json
packages/raf/src/index.ts
packages/raf/test/index.test.ts

I recently animated some SVGs and found the pattern helpful to create a milliseconds counter using createRAF and targetFPS, so I want to make this pattern an official primitive.

raf: add createMs primitive

---

.changeset/purple-coats-begin.md
packages/resize-observer/src/index.ts

Support for generics in `createResizeObserver` resolves #647

Use generics in `createResizeObserver`

---

.changeset/lovely-singers-rescue.md
packages/storage/src/persisted.ts

Fixes https://github.com/solidjs-community/solid-primitives/issues/652 - we only called `createUniqueId()` if no name, but a storage was given. In case of SSR without a defined storage, `createUniqueId()` would only be called in the client, which would lead to a hydration mismatch. Calling it before returning the signal/store in case no storage was given should fix this issue.

storage: fix ssr handling

---

.changeset/clean-mangos-camp.md
packages/resource/README.md
packages/resource/package.json
packages/resource/src/index.ts

Fixes https://github.com/solidjs-community/solid-primitives/issues/597 by adding createAbortable = makeAbortable + cleanup.

resource: new primitive createAbortable (makeAbortable + cleanup)

---

.changeset/selfish-eagles-train.md
packages/marker/src/index.ts

Fixes https://github.com/solidjs-community/solid-primitives/issues/681
Background: the - was removed after trimming, but it left the space at the end, so we got an empty capture, which caused memory leaks. Trimming the sanitized search string again fixes the issue.

fix: makeSearchRegex Memory leak (due to empty capture)

---

.changeset/short-buckets-visit.md
packages/workers/src/index.ts
packages/workers/src/types.d.ts
packages/workers/src/utils.ts

Hey all, this is my first PR to solid which is very exciting!
- Closes #594
- Is there anything to reconsider or change in here?
`types.d.ts` wasn't part of the entry point `index.ts` during the bundling process.
By importing and exporting the types from `index.d.ts` via `index.ts`, it will now bundle these types in the declaration file.
Here's the compiled types file in the relative `dist` directory:
```ts
import { Accessor, Setter } from 'solid-js';
type WorkerSignal = number;
type WorkerCallbacks = Map<string, [succes: Function, error: Function]>;
type WorkerMessage = {
type: WorkerSignal;
id?: string;
error?: string;
method?: string;
signal?: string | number;
result?: string;
params?: any;
};
type WorkerExports = [
worker: Worker,
start: () => void,
stop: () => void,
exports?: …
```

fix(workers): export missing types from definitions

---

.changeset/make-persisted-type-narrowing.md
packages/storage/src/persisted.ts

Fix `makePersisted` can't infer return type from the given signal created from `createSignal` and `createStore`
P.S. Seems like the tests are not testing types, maybe we should add it?

Fix `makePersisted` type narrowing

---

.changeset/three-windows-accept.md
packages/graphql/src/index.ts

fixes #545
fixes #389
fixes #504
Adds a `GraphQLError` error class, and throw it in case of a request error, instead of throwing an errors array.

graphql: Add a `GraphQLError` error class

---

.changeset/lemon-planets-try.md
packages/keyed/src/index.ts

I have an object whose keys are "[branded](https://www.learningtypescript.com/articles/branded-types)" strings, which are basically more strictly typed strings. This PR fixes the type of the key passed through to the callback.
I demo the new behavior in the screenshot below, where you can see the types in the inline hints:

Entries takes key's type as a generic

---

.changeset/unlucky-cars-yell.md
packages/virtual/README.md
packages/virtual/dev/index.tsx
packages/virtual/package.json
packages/virtual/src/index.tsx
packages/virtual/test/index.test.tsx
packages/virtual/test/server.test.tsx
pnpm-lock.yaml

As previously suggested, this is an attempt at rewriting the virtual list comp to be a headless utility function and adds tests and docs. It still exports the VirtualList comp for convenience, which uses the utility internally. The utility and comp are tested separately.
I think a lot of the TS in here is gross and people who know solid better than me might have better ideas for how to handle the ref. However, it does work and most of the ugliness is hidden from consumers. I don't really like the API, in terms of what you need to pass in and what comes back out and how you have to use it with the JSX, but I couldn't find anything to remove/add/simplify from/to/in it.

Headless virtual list

---

packages/tween/README.md

I used `@solid-primitives/tween` [the other day](https://github.com/edemaine/three-tiles/commit/a56f13867da62a1e9df3b942cdbb6594111b1449) and it was sooo lovely and simple. Well done: it was exactly what I wanted.
The docs fell a little short. Currently you need to read the code to know about the `ease` option, or to know how it works internally (`requestAnimationFrame`). So I fleshed out the README accordingly.
I couldn't test locally to see that the docs format OK.  When I tried `pnpm install; pnpm dev`, I got the error ``No packages found. Did you run `pnpm generate` ``. And `pnpm generate` fails (no such script). How do I generate the `src` directory?

tween docs: flesh out description, define all arguments

---

.changeset/perfect-jars-visit.md
packages/map/src/index.ts
packages/map/test/index.test.ts
packages/set/src/index.ts

This PR is improving and fixing ReactiveMap and ReactiveWeakMap, following up on https://github.com/solidjs-community/solid-primitives/pull/593
All noticeable changes have been commented. @thetarnav please let me know in case you have more questions :)

Fix and optimize ReactiveMap and ReactiveWeakMap

---

.changeset/silent-paws-approve.md
packages/static-store/src/index.ts
packages/static-store/test/index.test.ts

if a key is not listened to, setValue on that key incorrectly wraps the prev value in an array when passed as argument to a setterFn
```
const [state, setState] = createStaticStore({a: 1});
setState('a', prev => prev + 1); // prev is `[1]`, should be `1`
```

fix: static-store setValue with setterFn has correct arguments

---

.changeset/plenty-pears-sniff.md
packages/share/README.md
packages/share/package.json
packages/share/src/networks.ts

This PR adds Bluesky and X networks to the share package.

Adding Bluesky and X share package

---

.changeset/young-lizards-sing.md
packages/db-store/LICENSE
packages/db-store/README.md
packages/db-store/dev/index.tsx
packages/db-store/package.json
packages/db-store/src/index.ts
packages/db-store/test/index.test.ts
packages/db-store/test/supabase-mock.ts
packages/db-store/tsconfig.json
pnpm-lock.yaml

Originally, I wanted to add a database sync ability to storage, but the added amount of required serialization/deserialization was really bad for performance, so I pivoted to making a new package. This is basically an ORM implemented as a solid store featuring optimistic updates.
At the moment, there is only an adapter for supabase, but I intend to add at least mongodb soon to avoid vendor lock-in.

new package: db-store

---

packages/keyboard/README.md

the closing tag said `</kdb>` instead of `</kbd>`

fix kbd typo in keyboard readme

---

.changeset/light-boxes-cough.md
packages/selection/dev/index.tsx
packages/selection/src/index.ts

If you triple click on an li inside a list inside a contenteditable div (except for the last one), you get a selectionEnd of NaN. This is because for reasons unknown, in this case we receive the parent of the text node instead of the text node in the range.

fix: selection contenteditable node detection

---

.changeset/small-coats-obey.md
packages/resource/src/index.ts
packages/resource/test/index.test.ts

The setter of `createDeepSignal` is not working if you pass a non-function value.
```ts
const [data, { mutate }] = createResource(() => ({ counter: 1 }), {
storage: createDeepSignal,
});
// mutate(() => ({ counter: 2 })); // works
mutate({ counter: 2 }); // not working
createEffect(() => {
console.log(data()?.counter); // 1
});
```

Fix create deep signal

---

.changeset/funny-baths-drive.md
.changeset/red-islands-tickle.md
packages/map/src/index.ts
packages/map/test/index.test.ts
packages/set/src/index.ts
packages/set/test/index.test.ts

Listeners of non-existing members cannot observe different values before or after `.clear()` `.get(nonexsting) -> undefined` or `.has(nonexisting) -> false` so there's no use in notifying them.

Make ReactiveSet.clear() and ReactiveMap.clear() more efficient by only notifying listeners of existing members

---

.changeset/nasty-otters-camp.md
packages/mouse/src/common.ts

AFAIK, we want to use scrollY not screenY.

Typo makes `getPositionToScreen` buggy

---

.changeset/tender-mirrors-lay.md
packages/range/src/repeat.ts
packages/range/test/repeat.test.ts

Fixes #785
This substantially rewrites `repeat` to be more straight-forward with fewer closures, unlike #786 which is more conservative.

fix: repeat must not mutate its result object in place (#785)

---

site/src/routes/package/[name]/(package).tsx

Fix accessing correct stage path from `dataResource`/`cachedData` object in order to render stage badge correctly.
Before:
After:

Fix broken stage badge
