solidjs-community/solid-primitives

- package.json
- packages/fetch/test/index.test.ts
- packages/fetch/test/setup.ts
- yarn.lock
Fix the first tests for fetch as an example on how to write our tests.
> initial tests fix

- packages/stream/README.md
> Fix package name in README

- .gitignore
- packages/debounce/package.json
- packages/throttle/package.json
To solve the issue in #19 
This should work, but I don't know too much about building js, so I'm not totally sure.
> add commonjs build to debounce & throttle

- packages/devices/package.json
- packages/devices/test/index.test.ts
- packages/devices/test/setup.ts
Just moved the tests as they were in jest to be using uvu instead. Now the test works with the new lerna test script in #23
> update devices tests to use uvu

- packages/workers/README.md
```
--- ### createSignaledWprler
+++ ### createSignaledWorker
```
> Update README.md: small typo fix

- packages/geolocation/test/index.test.ts
Let's get tests all working. To run tests, for now run
```
npx lerna run test --concurrency 4
```
The other PR, #24, adds a script and automates it on GitHub Actions
> [WIP] fix tests

- README.md
> README copy editing

- packages/signal-builders/README.md
Reword how you wish; just that it was important to mention.
> Signal Builders: doc useMemo note

- README.md
- packages/composites/package.json
- packages/debounce/README.md
- packages/debounce/package.json
- packages/debounce/src/index.ts
- packages/debounce/test/index.test.ts
- packages/debounce/test/setup.ts
- packages/memo/package.json
- packages/memo/src/index.ts
- types, fixes issue#68
- working uvu test suite
- type tests
> debounce improvements

- .github/workflows/tests.yml
- package.json
- packages/input-mask/README.md
- packages/input-mask/dev/index.html
- packages/input-mask/dev/index.tsx
- packages/input-mask/package.json
- packages/input-mask/src/index.ts
- packages/media/package.json
- packages/raf/package.json
> handle/document onPaste event

- packages/storage/README.md
- packages/storage/package.json
- packages/storage/src/storage.ts
- packages/storage/src/types.ts
See https://discord.com/channels/722131463138705510/958428791124951050/963507468359585803
> storage: allow disabling sync events

- packages/storage/package.json
- packages/storage/src/storage.ts
- packages/storage/src/types.ts
- packages/storage/test/cookies.test.ts
- packages/storage/test/storage.test.ts
As discussed on discord, storage should handle errors gracefully.
> storage: error handling

- packages/selection/LICENSE
- packages/selection/README.md
- packages/selection/dev/index.html
- packages/selection/dev/index.tsx
- packages/selection/dev/vite.config.ts
- packages/selection/package.json
- packages/selection/src/index.ts
- packages/selection/test/index.test.tsx
- packages/selection/tsconfig.json
- packages/selection/tsup.config.ts
Selection inside textual inputs is simple; in contentEditable elements, it gets complicated. So simplification is a worthwile endeavor.
> new primitive: selection

- packages/fetch/README.md
- packages/fetch/package.json
- packages/fetch/src/index.ts
- packages/fetch/test/index.test.ts
for if you do not want to start a request right away
> feat: fetch allows undefined request info

- .github/workflows/format.yml
- package.json
Will format the codebase with prettier and commit it if there are changes.
Only on main branch.
> new github action: Format with prettier

- README.md
**What I Did**
Fix some typos in the main README
> fix some typos in the main README

- .changeset/fifty-frogs-buy.md
- packages/fetch/README.md
- packages/fetch/package.json
- packages/fetch/src/cache.ts
- packages/fetch/src/fetch.ts
- packages/fetch/src/index.ts
- packages/fetch/src/modifiers.ts
- packages/fetch/src/request.ts
- packages/fetch/src/server.ts
- packages/fetch/test/index.test.ts
- packages/fetch/test/setup.ts
> refetch on expiry

- .changeset/red-hornets-grow.md
- packages/stream/dev/index.tsx
- packages/stream/package.json
- packages/stream/src/index.ts
- packages/stream/src/server.ts
> implemented `createScreen`

- .changeset/breezy-crews-rhyme.md
- .changeset/twenty-emus-chew.md
- packages/scheduled/README.md
- packages/scheduled/package.json
- packages/scheduled/src/index.ts
- packages/scheduled/test/server.test.ts
Adds `scheduleIdle` scheduler based on `window.requestIdleCallback()`.
> Add `scheduleIdle` to `scheduled` package

- packages/intersection-observer/README.md
The demo is outdated. Pointing to the dev directory for the latest API. Alternatively, can Stackblitz be used to point to the dev directory?
> Update README.md of @solid-primitives/intersection-observer 

- .changeset/swift-taxis-rule.md
- packages/pagination/package.json
- packages/pagination/src/index.ts
- packages/pagination/test/index.test.ts
- packages/pagination/test/server.test.ts
https://github.com/solidjs-community/solid-primitives/pull/284 https://github.com/solidjs-community/solid-primitives/pull/285
> integrate pr#284 and pr#285

- .changeset/proud-eggs-hear.md
- packages/storage/package.json
- packages/storage/src/storage.ts
- pnpm-lock.yaml
Fixes hydration issue on `createStorageSignal `
> storage: fix hydration issue

- packages/memo/README.md
Changing "vary few" to "very few"
> Fix typo in memo/README.md

- package.json
- packages/script-loader/src/index.ts
- packages/script-loader/test/index.test.ts
- pnpm-lock.yaml
It's known to be impossible to test actual script loading with vitest and jsdom, so, naturally, I tried to work around that issue.
> test script loading

- .changeset/violet-toes-sleep.md
- packages/scroll/src/index.ts
reasoning: we don't preventDefault and the user cannot preventDefault
> use passive event listener for createScrollPosition

- .changeset/empty-crabs-repair.md
- packages/range/src/common.ts
- packages/range/src/indexRange.ts
- packages/range/src/mapRange.ts
- packages/range/src/repeat.ts
guess this one slipped through
> Fix range component types to support Solid 1.7

- .changeset/five-plums-yawn.md
- packages/input-mask/README.md
- packages/websocket/README.md
- packages/websocket/dev/index.html
- packages/websocket/dev/index.tsx
- packages/websocket/dev/vite.config.ts
- packages/websocket/package.json
- packages/websocket/src/index.ts
- packages/websocket/test/index.test.ts
- packages/websocket/test/setup.ts
Rewrote the primitive, with a lot of simplification and improved composability.
> Websocket rewrite

- .changeset/few-chicken-doubt.md
- packages/storage/README.md
- packages/storage/src/cookies.ts
- packages/storage/src/persisted.ts
Fixes https://github.com/solidjs-community/solid-primitives/issues/480
> storage: allow to finetune server behavior

- .changeset/clean-rivers-sparkle.md
- packages/i18n/src/i18n.ts
- packages/i18n/test/index.test.ts
- packages/i18n/test/setup.ts
Hello,
A little PR to add support for translations with dot for this issue #382
> translate key with dot

- packages/websocket/README.md
> Docs: typo (craete => create)

- packages/keyed/README.md
I hate people that just make changes to README.md so it says on their github profile that they contributed but I legit got confused what singlas are and thought this (a PR) was more helpful than opening an issue
> singlas -> signals in Readme

- .changeset/plenty-teachers-drum.md
- packages/pagination/src/index.ts
- packages/pagination/test/index.test.ts
Back was always returning first page and next was returning last page.
This pr fixes that.
> Fix of back and next page values

- .changeset/polite-cups-attack.md
- packages/fetch/src/index.ts
Fix import modifer `withAggregation` was missing.
> fix: fetch index.ts import

- .changeset/chatty-balloons-end.md
- packages/immutable/README.md
- packages/immutable/package.json
- packages/immutable/src/index.ts
- packages/immutable/test/index.test.ts
This is needed for https://github.com/statelyai/xstate/pull/4680
> immutable: Support storing other class instances than plain objects.

- packages/i18n/src/index.ts
- packages/i18n/test/index.test.ts
- packages/i18n/test/server.test.ts
- packages/i18n/test/setup.tsx
Continues https://github.com/solidjs-community/solid-primitives/pull/568
@BierDav
> Add support for Generic Template Resolvers

- packages/scheduled/dev/timeline.tsx
Changed the scheduled DEMO to make it easier to understand.
Specifically, each cell is now colored in the same color when the source is the same.
> Colorize scheduled playground

- .changeset/cyan-bulldogs-scream.md
- packages/storage/README.md
- packages/storage/package.json
- packages/storage/src/cookies.ts
- packages/storage/src/index.ts
- packages/storage/src/persisted.ts
- packages/storage/src/tools.ts
- packages/storage/src/types.ts
- pnpm-lock.yaml
This is a major rework of the storage/persistence API and the first step before fully deprecating the old APIs. This adds the sync API and muxers (multiplerxers) for sync and storage and also a withOptions method that makes handling cookieStorage with options a lot more convenient.
This needs more documentation (ie. recipes how to use cookieStorage on a server with solid classic SSR instead of solid-start).
> Storage reloaded

- .changeset/fuzzy-beans-drum.md
- packages/storage/src/cookies.ts
Shame on me. I forgot to use the new helper I created and even advertised its abilities before making them available...
OK, let's rectify this.
> add withOptions method to cookieStorage

- .changeset/brown-students-divide.md
- packages/storage/src/persisted.ts
addresses https://github.com/solidjs-community/solid-primitives/issues/599
> storage: safe sync deserialization

- packages/list/test/index.bench.tsx
The performance should not be much worse than For. This benchmark shows it's ~1.25x slower, which is acceptable.
> list: add benchmark

- .changeset/light-dogs-yawn.md
- packages/storage/src/cookies.ts
- packages/storage/test/cookies.test.ts
FIxes https://github.com/solidjs-community/solid-primitives/issues/530
> storage: fix cookie serialization

- .changeset/hot-llamas-compete.md
- packages/script-loader/src/index.ts
> script-loader: fix events

- .changeset/perfect-oranges-work.md
- packages/promise/src/index.ts
- packages/promise/test/intex.test.ts
> Handle rejected promises with raceTimeout #635

- .changeset/rich-cougars-explode.md
- packages/storage/README.md
- packages/storage/src/cookies.ts
- packages/storage/test/cookies.test.ts
fixes https://github.com/solidjs-community/solid-primitives/issues/673
> storage: escape utf-8 cookies correctly

- packages/input-mask/dev/index.tsx
I wanted to add an example how to format numeric fields because that was an ask previously.
> docs: input mask money example

- .changeset/fresh-points-join.md
- packages/scheduled/src/index.ts
Add check for typeof window, fallback to throttle if undefined
> schedule - Add check for typeof window, fallback to throttle if undefined

- site/src/routes/index.tsx
> fix: stage badge
